    name: UAStaffChat
    main: tk.thediamondpicks.sc.Chat
    author: TheDiamondPicks
    website: http://thediamondpicks.tk
    version: 2.1
    commands:
     screload:
      desciption: Reload the configuration
      aliases: [scr]
      usage: /screload or /scr
     csc:
      desciption: Allows the console to execute chat commands
      usage: /csc [name of chat] [message]